version: '2.4'
services:
  app:
    build:                                  # Uncomment to enable local build
      context: .
      dockerfile: ./Dockerfile
      args:
        PY_VER: $PY_VER
        CONDA_VER: $CONDA_VER
        JUPYTER_HUB_IMAGE: "false"
      # dockerfile: ./test.dockerfile
    image: datajoint/conda-docker:${CONDA_VER}-python${PY_VER}-alpine
    # image: datajoint/conda-docker:4.7.5-python${PY_VER}-alpine
    # image: test:1
    environment:
      - DISPLAY                             # Necessary to allow GUI to route to Docker host
      - PYTHON_USER=dja                     # Underprivileged username
      - JUPYTER_PASSWORD=test          # Jupyter Notebook login password
    ports:
      - 8888:8888
    # command: tail -f /dev/null               # Container command e.g. here serving ipynb
    command: jupyter notebook
    user: ${UID}:anaconda                   # Necessary to allow GUI to route to Docker host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw    # Necessary to allow GUI to route to Docker host
      - ./apk_requirements.txt:/apk_requirements.txt
